### ISSUE TITLE
Fails to build with Clang

### ISSUE THREAD

**Issue by jbeich** [intel/intel-graphics-compiler#157]
Regressed by d0874824631f and 5c46a2ad5933. From [error log](https://github.com/intel/intel-graphics-compiler/files/5665750/intel-graphics-compiler-1.0.5761.86.log):
```c++
$ export CC=clang CXX=clang++
$ cmake
$ make
[...]
IGC/VectorCompiler/lib/GenXCodeGen/GenXLowering.cpp:2527:12: error: reference to local binding 'IsSignedOps' declared in enclosing function '(anonymous namespace)::GenXLowering::lowerMulSat'
    return IsSignedOps ? B.CreateSExt(Val, MulType, Val->getName() + ".sext")
           ^
IGC/VectorCompiler/lib/GenXCodeGen/GenXLowering.cpp:2507:22: note: 'IsSignedOps' declared here
  auto [IsSignedRes, IsSignedOps] = IsSignedMulSat(IntrinsicID);
                     ^
IGC/VectorCompiler/lib/GenXCodeGen/ConstantEncoder.h:212:38: error: member reference base type 'ConstantEncoder' is not a structure or union
  return ConstantEncoder{DL, OutIter}.encode(Const);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

**Comment by pszymich** [comment]
Hello Jan,

We've reviewed your pull request and decided to merge it.
Due to our processes we had to have your pull request mirrored internally. The change is the same, authored by you, but we will have to close the one you provided.

Thank you for your contribution!
