### ISSUE TITLE
1.0.5585 fails to build against LLVM 11

### ISSUE THREAD

**Issue by jbeich** [intel/intel-graphics-compiler#155]
Regressed by 150427ee0750. From [error log](https://github.com/intel/intel-graphics-compiler/files/5590832/intel-graphics-compiler-1.0.5585.log):
```c++
In file included from IGC/VectorCompiler/lib/GenXOpts/CMPacketize/PacketBuilder.h:40:
IGC/WrapperLLVM/include/llvmWrapper/Support/Alignment.h:93:16: error: no viable conversion from returned value of type 'llvm::MaybeAlign' to function return type 'IGCLLVM::Align' (aka 'llvm::Align')
        return Val.getAlign();
               ^~~~~~~~~~~~~~
IGC/VectorCompiler/lib/GenXOpts/CMPacketize/GenXPacketize.cpp:279:37: note: in instantiation of function template specialization 'IGCLLVM::getAlign<llvm::Function, 0>' requested here
  ClonedFunc->setAlignment(IGCLLVM::getAlign(*F));
                                    ^
/usr/include/llvm/Support/Alignment.h:71:13: note: candidate constructor not viable: no known conversion from 'llvm::MaybeAlign' to 'const llvm::Align &' for 1st argument
  constexpr Align(const Align &Other) = default;
            ^
/usr/include/llvm/Support/Alignment.h:72:13: note: candidate constructor not viable: no known conversion from 'llvm::MaybeAlign' to 'llvm::Align &&' for 1st argument
  constexpr Align(Align &&Other) = default;
            ^
/usr/include/llvm/Support/Alignment.h:109:13: note: candidate constructor not viable: no known conversion from 'llvm::MaybeAlign' to 'llvm::Align::LogValue' for 1st argument
  constexpr Align(LogValue CA) : ShiftValue(CA.Log) {}
            ^
1 error generated.
```
I've tried to revert 150427ee0750 only to bump into 07d74a97efb7 regression:
```c++
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:83:28: error: use of undeclared identifier 'AAResultsWrapperPass'
            AU.addRequired<AAResultsWrapperPass>();
                           ^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:83:49: error: expected unqualified-id
            AU.addRequired<AAResultsWrapperPass>();
                                                ^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:706:5: error: unknown type name 'AliasAnalysis'
    AliasAnalysis* AA = &getAnalysis<AAResultsWrapperPass>().getAAResults();
    ^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:706:38: error: use of undeclared identifier 'AAResultsWrapperPass'
    AliasAnalysis* AA = &getAnalysis<AAResultsWrapperPass>().getAAResults();
                                     ^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:781:27: error: use of undeclared identifier 'MemoryLocation'; did you mean 'TempDILocation'?
            if (AA->alias(MemoryLocation::get(SI), MemoryLocation::get(LI))) {
                          ^~~~~~~~~~~~~~
                          TempDILocation
/usr/include/llvm/IR/Metadata.def:82:1: note: 'TempDILocation' declared here
HANDLE_SPECIALIZED_MDNODE_LEAF_UNIQUABLE(DILocation)
^
/usr/include/llvm/IR/Metadata.def:46:3: note: expanded from macro 'HANDLE_SPECIALIZED_MDNODE_LEAF_UNIQUABLE'
  HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS)
  ^
/usr/include/llvm/IR/Metadata.def:67:47: note: expanded from macro 'HANDLE_SPECIALIZED_MDNODE_LEAF'
#define HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS) HANDLE_MDNODE_LEAF(CLASS)
                                              ^
/usr/include/llvm/IR/Metadata.h:850:9: note: expanded from macro 'HANDLE_MDNODE_LEAF'
  using Temp##CLASS = std::unique_ptr<CLASS, TempMDNodeDeleter>;
        ^
<scratch space>:15:1: note: expanded from here
TempDILocation
^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:781:43: error: call to non-static member function without an object argument
            if (AA->alias(MemoryLocation::get(SI), MemoryLocation::get(LI))) {
                          ~~~~~~~~~~~~~~~~^~~
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:781:52: error: use of undeclared identifier 'MemoryLocation'; did you mean 'TempDILocation'?
            if (AA->alias(MemoryLocation::get(SI), MemoryLocation::get(LI))) {
                                                   ^~~~~~~~~~~~~~
                                                   TempDILocation
/usr/include/llvm/IR/Metadata.def:82:1: note: 'TempDILocation' declared here
HANDLE_SPECIALIZED_MDNODE_LEAF_UNIQUABLE(DILocation)
^
/usr/include/llvm/IR/Metadata.def:46:3: note: expanded from macro 'HANDLE_SPECIALIZED_MDNODE_LEAF_UNIQUABLE'
  HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS)
  ^
/usr/include/llvm/IR/Metadata.def:67:47: note: expanded from macro 'HANDLE_SPECIALIZED_MDNODE_LEAF'
#define HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS) HANDLE_MDNODE_LEAF(CLASS)
                                              ^
/usr/include/llvm/IR/Metadata.h:850:9: note: expanded from macro 'HANDLE_MDNODE_LEAF'
  using Temp##CLASS = std::unique_ptr<CLASS, TempMDNodeDeleter>;
        ^
<scratch space>:15:1: note: expanded from here
TempDILocation
^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:781:68: error: call to non-static member function without an object argument
            if (AA->alias(MemoryLocation::get(SI), MemoryLocation::get(LI))) {
                                                   ~~~~~~~~~~~~~~~~^~~
8 errors generated.
```

**Comment by jbeich** [comment]
Sorry, my guess about regressing commit was wrong. I've edited it out.

**Comment by jbeich** [comment]
Bisecting led to 150427ee075023dfe

**Comment by jbeich** [comment]
Reverting 150427ee0750 exposes 07d74a97efb7 regression:
```c++
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:83:28: error: use of undeclared identifier 'AAResultsWrapperPass'
            AU.addRequired<AAResultsWrapperPass>();
                           ^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:83:49: error: expected unqualified-id
            AU.addRequired<AAResultsWrapperPass>();
                                                ^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:706:5: error: unknown type name 'AliasAnalysis'
    AliasAnalysis* AA = &getAnalysis<AAResultsWrapperPass>().getAAResults();
    ^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:706:38: error: use of undeclared identifier 'AAResultsWrapperPass'
    AliasAnalysis* AA = &getAnalysis<AAResultsWrapperPass>().getAAResults();
                                     ^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:781:27: error: use of undeclared identifier 'MemoryLocation'; did you mean 'TempDILocation'?
            if (AA->alias(MemoryLocation::get(SI), MemoryLocation::get(LI))) {
                          ^~~~~~~~~~~~~~
                          TempDILocation
/usr/include/llvm/IR/Metadata.def:82:1: note: 'TempDILocation' declared here
HANDLE_SPECIALIZED_MDNODE_LEAF_UNIQUABLE(DILocation)
^
/usr/include/llvm/IR/Metadata.def:46:3: note: expanded from macro 'HANDLE_SPECIALIZED_MDNODE_LEAF_UNIQUABLE'
  HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS)
  ^
/usr/include/llvm/IR/Metadata.def:67:47: note: expanded from macro 'HANDLE_SPECIALIZED_MDNODE_LEAF'
#define HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS) HANDLE_MDNODE_LEAF(CLASS)
                                              ^
/usr/include/llvm/IR/Metadata.h:850:9: note: expanded from macro 'HANDLE_MDNODE_LEAF'
  using Temp##CLASS = std::unique_ptr<CLASS, TempMDNodeDeleter>;
        ^
<scratch space>:15:1: note: expanded from here
TempDILocation
^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:781:43: error: call to non-static member function without an object argument
            if (AA->alias(MemoryLocation::get(SI), MemoryLocation::get(LI))) {
                          ~~~~~~~~~~~~~~~~^~~
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:781:52: error: use of undeclared identifier 'MemoryLocation'; did you mean 'TempDILocation'?
            if (AA->alias(MemoryLocation::get(SI), MemoryLocation::get(LI))) {
                                                   ^~~~~~~~~~~~~~
                                                   TempDILocation
/usr/include/llvm/IR/Metadata.def:82:1: note: 'TempDILocation' declared here
HANDLE_SPECIALIZED_MDNODE_LEAF_UNIQUABLE(DILocation)
^
/usr/include/llvm/IR/Metadata.def:46:3: note: expanded from macro 'HANDLE_SPECIALIZED_MDNODE_LEAF_UNIQUABLE'
  HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS)
  ^
/usr/include/llvm/IR/Metadata.def:67:47: note: expanded from macro 'HANDLE_SPECIALIZED_MDNODE_LEAF'
#define HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS) HANDLE_MDNODE_LEAF(CLASS)
                                              ^
/usr/include/llvm/IR/Metadata.h:850:9: note: expanded from macro 'HANDLE_MDNODE_LEAF'
  using Temp##CLASS = std::unique_ptr<CLASS, TempMDNodeDeleter>;
        ^
<scratch space>:15:1: note: expanded from here
TempDILocation
^
IGC/Compiler/CISACodeGen/ResolveGAS.cpp:781:68: error: call to non-static member function without an object argument
            if (AA->alias(MemoryLocation::get(SI), MemoryLocation::get(LI))) {
                                                   ~~~~~~~~~~~~~~~~^~~
8 errors generated.
```

**Comment by pszymich** [comment]
Hello,

We don't support building against LLVM 11 yet.
Please check out comments in this issue: https://github.com/intel/intel-graphics-compiler/issues/152
Also, we provide information on LLVM compatibility in our [build_ubuntu.md](https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md#llvmclang-version-information) documentation file.
