### ISSUE TITLE
Fails to build with Clang 10.0

### ISSUE THREAD

**Issue by jbeich** [intel/intel-graphics-compiler#126]
```c++
$ export CC=clang10 CXX=clang++10
$ cmake -GNinja /path/to/intel-graphics-compiler
$ ninja
[...]
In file included from IGC/Compiler/CISACodeGen/PreRAScheduler.cpp:37:
In file included from IGC/Compiler/CISACodeGen/PreRAScheduler.hpp:29:
In file included from IGC/Compiler/CISACodeGen/ShaderCodeGen.hpp:28:
In file included from IGC/Compiler/CISACodeGen/CVariable.hpp:28:
In file included from IGC/Compiler/CISACodeGen/CISABuilder.hpp:27:
In file included from IGC/Compiler/CISACodeGen/CISACodeGen.h:27:
In file included from IGC/Compiler/CodeGenPublic.h:43:
In file included from IGC/Compiler/CISACodeGen/helper.h:50:
In file included from IGC/Compiler/MetaDataApi/MetaDataApi.h:31:
In file included from IGC/Compiler/MetaDataApi/MetaDataApiUtils.h:29:
IGC/Compiler/MetaDataApi/MetaDataValue.h:81:20: error: cannot initialize return object of type 'llvm::MDNode *' with an lvalue of type 'llvm::Metadata *'
            return m_pNode;
                   ^~~~~~~
IGC/Compiler/MetaDataApi/MetaDataValue.h:259:23: error: assigning to 'llvm::Metadata *' from incompatible type 'llvm::Value *'
            m_pNode = pNode;
                      ^~~~~
IGC/Compiler/MetaDataApi/MetaDataValue.h:269:18: error: no viable overloaded '='
            m_id = name;
            ~~~~ ^ ~~~~
IGC/Compiler/MetaDataApi/MetaDataValue.h:40:11: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'const char *' to 'const IGC::MetaDataValue<std::__1::basic_string<char>, IGC::MDValueTraits<std::string, void> >' for 1st argument
    class MetaDataValue
          ^
IGC/Compiler/MetaDataApi/MetaDataValue.h:40:11: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'const char *' to 'IGC::MetaDataValue<std::__1::basic_string<char>, IGC::MDValueTraits<std::string, void> >' for 1st argument
    class MetaDataValue
          ^
IGC/Compiler/MetaDataApi/MetaDataValue.h:277:18: error: no viable overloaded '='
            m_id = name.c_str();
            ~~~~ ^ ~~~~~~~~~~~~
IGC/Compiler/MetaDataApi/MetaDataValue.h:40:11: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') to 'const IGC::MetaDataValue<std::__1::basic_string<char>, IGC::MDValueTraits<std::string, void> >' for 1st argument
    class MetaDataValue
          ^
IGC/Compiler/MetaDataApi/MetaDataValue.h:40:11: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') to 'IGC::MetaDataValue<std::__1::basic_string<char>, IGC::MDValueTraits<std::string, void> >' for 1st argument
    class MetaDataValue
          ^
4 errors generated.
```
http://package18.nyi.freebsd.org/data/headamd64244251-default/2020-02-24_21h29m01s/logs/errors/intel-graphics-compiler-1.0.3342.log

**Comment by jbeich** [comment]
Full build log: http://package18.nyi.freebsd.org/data/headamd64244251-default/2020-02-24_21h29m01s/logs/errors/intel-graphics-compiler-1.0.3342.log

**Comment by servesh** [comment]
This issue is also seen with debug build with GCC 9.3 in the recent commits.

**Comment by jbeich** [comment]
Fixed by c94066f10aa8.
