### PR TITLE
Unbreak build with Clang

### LINKED ISSUE #126: Fails to build with Clang 10.0
```c++
$ export CC=clang10 CXX=clang++10
$ cmake -GNinja /path/to/intel-graphics-compiler
$ ninja
[...]
In file included from IGC/Compiler/CISACodeGen/PreRAScheduler.cpp:37:
In file included from IGC/Compiler/CISACodeGen/PreRAScheduler.hpp:29:
In file included from IGC/Compiler/CISACodeGen/ShaderCodeGen.hpp:28:
In file included from IGC/Compiler/CISACodeGen/CVariable.hpp:28:
In file included from IGC/Compiler/CISACodeGen/CISABuilder.hpp:27:
In file included from IGC/Compiler/CISACodeGen/CISACodeGen.h:27:
In file included from IGC/Compiler/CodeGenPublic.h:43:
In file included from IGC/Compiler/CISACodeGen/helper.h:50:
In file included from IGC/Compiler/MetaDataApi/MetaDataApi.h:31:
In file included from IGC/Compiler/MetaDataApi/MetaDataApiUtils.h:29:
IGC/Compiler/MetaDataApi/MetaDataValue.h:81:20: error: cannot initialize return object of type 'llvm::MDNode *' with an lvalue of type 'llvm::Metadata *'
            return m_pNode;
                   ^~~~~~~
IGC/Compiler/MetaDataApi/MetaDataValue.h:259:23: error: assigning to 'llvm::Metadata *' from incompatible type 'llvm::Value *'
            m_pNode = pNode;
                      ^~~~~
IGC/Compiler/MetaDataApi/MetaDataValue.h:269:18: error: no viable overloaded '='
            m_id = name;
            ~~~~ ^ ~~~~
IGC/Compiler/MetaDataApi/MetaDataValue.h:40:11: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'const char *' to 'const IGC::MetaDataValue<std::__1::basic_string<char>, IGC::MDValueTraits<std::string, void> >' for 1st argument
    class MetaDataValue
          ^
IGC/Compiler/MetaDataApi/MetaDataValue.h:40:11: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'const char *' to 'IGC::MetaDataValue<std::__1::basic_string<char>, IGC::MDValueTraits<std::string, void> >' for 1st argument
    class MetaDataValue
          ^
IGC/Compiler/MetaDataApi/MetaDataValue.h:277:18: error: no viable overloaded '='
            m_id = name.c_str();
            ~~~~ ^ ~~~~~~~~~~~~
IGC/Compiler/MetaDataApi/MetaDataValue.h:40:11: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') to 'const IGC::MetaDataValue<std::__1::basic_string<char>, IGC::MDValueTraits<std::string, void> >' for 1st argument
    class MetaDataValue
          ^
IGC/Compiler/MetaDataApi/MetaDataValue.h:40:11: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *') to 'IGC::MetaDataValue<std::__1::basic_string<char>, IGC::MDValueTraits<std::string, void> >' for 1st argument
    class MetaDataValue
          ^
4 errors generated.
```
http://package18.nyi.freebsd.org/data/headamd64244251-default/2020-02-24_21h29m01s/logs/errors/intel-graphics-compiler-1.0.3342.log

### LINKED ISSUE #157: Fails to build with Clang
Regressed by d0874824631f and 5c46a2ad5933. From [error log](https://github.com/intel/intel-graphics-compiler/files/5665750/intel-graphics-compiler-1.0.5761.86.log):
```c++
$ export CC=clang CXX=clang++
$ cmake
$ make
[...]
IGC/VectorCompiler/lib/GenXCodeGen/GenXLowering.cpp:2527:12: error: reference to local binding 'IsSignedOps' declared in enclosing function '(anonymous namespace)::GenXLowering::lowerMulSat'
    return IsSignedOps ? B.CreateSExt(Val, MulType, Val->getName() + ".sext")
           ^
IGC/VectorCompiler/lib/GenXCodeGen/GenXLowering.cpp:2507:22: note: 'IsSignedOps' declared here
  auto [IsSignedRes, IsSignedOps] = IsSignedMulSat(IntrinsicID);
                     ^
IGC/VectorCompiler/lib/GenXCodeGen/ConstantEncoder.h:212:38: error: member reference base type 'ConstantEncoder' is not a structure or union
  return ConstantEncoder{DL, OutIter}.encode(Const);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

### PR DESCRIPTION
**Pull request by jbeich**
Fixes #157

### CODE REVIEW

**Comment by NaruFGT** [comment]
This fixes the build for me, though I also had to modify CMakeLists.txt and add `-Wno-inconsistent-missing-override`

**Comment by pszymich** [comment]
Hello Jan,

We've merged your pull-request internally and I'm closing this one.
Link to the pull-request commit: https://github.com/intel/intel-graphics-compiler/commit/a170679c0c9ab78cd2f2cdedcc281323ca8c4d9a

Thank you for the contribution!
